# Generated by Django 5.0.3 on 2024-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('fotos', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lanches',
            },
        ),
    ]
