# Generated by Django 5.0.3 on 2024-03-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioadmin_alter_lanche_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadmin',
            name='chave_criptografia',
        ),
    ]
