# Generated by Django 5.0.3 on 2024-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuarioadmin_chave_criptografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSimple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('email_cifrado', models.EmailField(max_length=254)),
                ('senha_hash', models.TextField()),
                ('endereco', models.TextField()),
                ('cep', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usersimple',
            },
        ),
    ]
