# Generated by Django 3.2.12 on 2024-04-03 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuariosimple'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadmin',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
