# Generated by Django 5.0.3 on 2024-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuarioadmin_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosimple',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
