# Generated by Django 5.0.3 on 2024-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ip_visualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=100)),
                ('collection_status', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(max_length=100)),
                ('merchant_order_id', models.CharField(max_length=100)),
                ('preference_id', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('processing_mode', models.CharField(max_length=100)),
                ('merchant_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
